### ISSUE TITLE
Error when using NgetSolverTemplate

### ISSUE THREAD

**Issue by FlorianSchwendinger** [bpfaff/rneos#1]
Dear Bernhard Pfaff, 

Till last week **rneos** did work perfectly but today I recognized that when I try to use `NgetSolverTemplate` I get an error message.

```r
library(rneos)

tmp <- NgetSolverTemplate(category = "go", solvername = "ASA", inputMethod = "AMPL")
## Error: faultCode:  1  faultString:  <type 'exceptions.TypeError'>:getHelpTemplate() takes at least 3 arguments (3 given)
```

I tried it with the R versions 3.3.3 and 3.4.0 and get always the same error.

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

Matrix products: default
BLAS: /home/florian/bin/R_dev/lib/libRblas.so
LAPACK: /home/florian/bin/R_dev/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rneos_0.3-2    XML_3.98-1.9   RCurl_1.95-4.7 bitops_1.0-6  

loaded via a namespace (and not attached):
[1] compiler_3.4.0 XMLRPC_0.3-0 
```

Have you any idea why this error occurs and can you reproduce it?

Best,
Florian

**Comment by bpfaff** [comment]
Hi Florian,

many thanks for your email and alerting me to this error message.
I can replicate this error and it is a bit irritating, because all
arguments are provided in the call to xmlrpc().
I am not sure, whether the maintainers of the NEOS API have made some
(undocumented) changes to the API. Hence, I will contact them in due
course and see how this issue can be resolved.

Best wishes,
Bernhard

**Comment by bpfaff** [comment]
Hi Florian,

good news, the NEOS-support team has fixed the bug and everything is
working as expected.

Best wishes,
Bernhard

**Comment by FlorianSchwendinger** [comment]
Sounds great.
Thank you!
